image: freebsd
packages:
  - go
environment:
  GO111MODULE: 'on'
sources:
  - https://git.sr.ht/~samwhited/cli
tasks:
  - test: |
      cd cli/
      go build
      go vet ./...
      go test -cover ./...
