image: freebsd
packages:
  - go
environment:
  GO111MODULE: 'on'
sources:
  - https://git.sr.ht/~samwhited/cli
tasks:
  - setup: |
      export PATH=$(go env GOPATH)/bin:$PATH
      echo 'export PATH=$(go env GOPATH)/bin:$PATH' >> ~/.buildenv

      GO111MODULE=off go get golang.org/dl/go1.10.7
      GO111MODULE=off go get golang.org/dl/go1.11.4
      GO111MODULE=off go get golang.org/dl/gotip
      go1.10.7 download
      go1.11.4 download
      gotip download
  - vet: |
      cd cli/
      go vet ./...
  - go110: |
      mkdir -p `go env GOPATH`/src/mellium.im/
      ln -s `pwd`/cli/ `go env GOPATH`/src/mellium.im/cli
      cd `go env GOPATH`/src/mellium.im/cli
      go1.10.7 env
      go1.10.7 test -cover ./...
  - go111: |
      cd cli/
      go1.11.4 env
      go1.11.4 test -cover ./...
  - gotip: |
      cd cli/
      gotip env
      gotip test -cover ./...
