name: Close Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/auto-close-action@c9be55e32fb1bc2e40207afe5e103f891799334e
      with:
        comment: "This repo is a mirror and does not accept PRs. See `README.md` for more information. Thanks for contributing!"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
